# Generated by Django 4.2.7 on 2023-11-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('isbn', models.BigIntegerField()),
                ('number_of_pages', models.BigIntegerField()),
                ('language', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
